name: PacketEventsDetector
version: ${version}
main: com.deathmotion.packeteventsdetector.PacketEventsDetector
api-version: '1.21'
folia-supported: true
author: "Bram"
description: Plugin that tries to detect plugins that shade PacketEvents.
load: POSTWORLD